# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, related_name='class_teachers', to='teachers.Teachers'),
        ),
    ]
