# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_stream__class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.Classes'),
            preserve_default=False,
        ),
    ]
