# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20170613_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='schools.Schools'),
        ),
    ]
