# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_auto_20170928_1346'),
        ('stream', '0003_auto_20170928_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduatesStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(max_length=4)),
                ('class_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_streams', to='schools.Schools')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='graduatesstream',
            unique_together=set([('school', 'year')]),
        ),
    ]
