# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-30 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_auto_20171113_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='last_attendance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
