# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('one_time', models.BooleanField(default=False)),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
            ],
        ),
    ]
