# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='school_id',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
