# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_id',
        ),
        migrations.AddField(
            model_name='classes',
            name='class_name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='classes',
            name='school_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Schools'),
        ),
    ]
