# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20170109_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_name',
            field=models.CharField(max_length=200),
        ),
    ]
