# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20170410_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
