# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constituencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constituencies',
            old_name='Cons_name',
            new_name='cons_name',
        ),
        migrations.RemoveField(
            model_name='constituencies',
            name='cons_id',
        ),
        migrations.AlterField(
            model_name='constituencies',
            name='county_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counties.Counties'),
        ),
    ]
