# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constituencies', '0002_auto_20161025_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constituencies',
            old_name='cons_name',
            new_name='constituency',
        ),
    ]
