# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constituencies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_code', models.IntegerField(default=0)),
                ('school_name', models.CharField(default='schoolname', max_length=200)),
                ('geo_cordinates', models.CharField(max_length=200)),
                ('emis_code', models.IntegerField(default=0)),
                ('source_of_water', models.CharField(max_length=200)),
                ('headteacher', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField(default=0)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constituencies.Constituencies')),
            ],
        ),
    ]
