# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.IntegerField(default=0)),
                ('school_code', models.IntegerField(default=0)),
                ('school_name', models.CharField(max_length=200)),
                ('geo_cordinates', models.IntegerField(default=0)),
                ('emis_code', models.IntegerField(default=0)),
                ('const_id', models.IntegerField(default=0)),
                ('source_of_water', models.CharField(max_length=200)),
            ],
        ),
    ]
