# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constituencies', '0002_auto_20161025_2239'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='const_id',
        ),
        migrations.RemoveField(
            model_name='schools',
            name='school_id',
        ),
        migrations.AddField(
            model_name='schools',
            name='cons_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='constituencies.Constituencies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schools',
            name='headteacher',
            field=models.CharField(default='fullnames', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schools',
            name='phone_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schools',
            name='geo_cordinates',
            field=models.CharField(max_length=200),
        ),
    ]
