# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='emis_code',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
