# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20170109_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='constituency',
        ),
        migrations.AddField(
            model_name='schools',
            name='level',
            field=models.CharField(choices=[(b'PRIMARY', b'Primary'), (b'SECONADRY', b'Secondary')], default=b'PRIMARY', max_length=50),
        ),
        migrations.AddField(
            model_name='schools',
            name='status',
            field=models.CharField(choices=[(b'PUBLIC', b'Public'), (b'PRIVATE', b'Private')], default=b'PUBLIC', max_length=50),
        ),
    ]
