# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-13 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('schools', '0002_auto_20170527_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partner.Partner'),
        ),
    ]
