# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_schools__class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='_class',
        ),
    ]
