# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20161025_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='cons_name',
        ),
    ]
