# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_partner_phone'),
        ('schools', '0003_schools_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='partner',
        ),
        migrations.AddField(
            model_name='schools',
            name='partners',
            field=models.ManyToManyField(blank=True, null=True, to='partner.Partner'),
        ),
    ]
