# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
        ('schools', '0003_auto_20170115_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zone.Zone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schools',
            name='geo_cordinates',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schools',
            name='source_of_water',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
