# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_remove_schools__class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_name',
            field=models.CharField(max_length=200),
        ),
    ]
