# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20170621_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='partners',
            field=models.ManyToManyField(blank=True, null=True, related_name='schools', to='partner.Partner'),
        ),
    ]
