# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_schools_cons_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='school_name',
            field=models.CharField(default='schoolname', max_length=200),
        ),
    ]
