# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20170115_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='level',
            field=models.CharField(choices=[(b'PRIMARY', b'Primary'), (b'SECONDARY', b'Secondary')], default=b'PRIMARY', max_length=50),
        ),
    ]
