# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-29 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcounty', '0002_auto_20170822_1826'),
        ('schools', '0006_auto_20180129_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='subcounty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subcounty.SubCounty'),
        ),
    ]
