# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_auto_20170122_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='geo_cordinates',
        ),
        migrations.AddField(
            model_name='schools',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schools',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
