# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-01 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_auto_20180226_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='partner_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
