# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-22 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_schools_partner_conflict'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
