# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotions',
            name='promotion_id',
            field=models.IntegerField(default=0),
        ),
    ]
