# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_promotions_promotion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
    ]
