# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-13 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_auto_20171113_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoteschool',
            name='promotions',
        ),
        migrations.AddField(
            model_name='promotestream',
            name='promote_school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promotions.PromoteSchool'),
            preserve_default=False,
        ),
    ]
