# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_auto_20171113_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotestream',
            name='promote_school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_promotions', to='promotions.PromoteSchool'),
        ),
        migrations.AlterUniqueTogether(
            name='promoteschool',
            unique_together=set([]),
        ),
    ]
