# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-02 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counties',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counties',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
