# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='absence',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
