# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='absence',
            name='reasons',
            field=models.ManyToManyField(blank=True, null=True, to='reason.Reason'),
        ),
    ]
