# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('absence', '0002_auto_20170430_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='_class',
            field=models.ForeignKey(default=92, on_delete=django.db.models.deletion.CASCADE, to='classes.Classes'),
            preserve_default=False,
        ),
    ]
