# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0003_absence__class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='_class',
            field=models.CharField(default='y', max_length=20),
        ),
    ]
