# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-30 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('absence', '0004_auto_20170430_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absence',
            name='_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Classes'),
        ),
    ]
