# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcounty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcounty',
            name='county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='counties.Counties'),
        ),
    ]
