# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-16 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='admission_no',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='emis_code',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
