# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='emis_code_histries',
            new_name='emis_code_histories',
        ),
        migrations.RemoveField(
            model_name='students',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='students',
            name='school_id',
        ),
        migrations.AlterField(
            model_name='students',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Classes'),
        ),
    ]
