# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170110_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='total_attendance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
