# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20170616_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='is_oosc',
            field=models.BooleanField(default=False),
        ),
    ]
