# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20170110_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='absence',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
