# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-04 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_students_is_oosc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='lstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
