# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-22 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20170705_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='emis_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='student_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
