# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20170116_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='last_attendance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
