# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_students_last_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='student_name',
            new_name='fstname',
        ),
        migrations.AddField(
            model_name='students',
            name='lstname',
            field=models.CharField(default='Jonh', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='midname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
