# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20170915_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='household',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
