# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-18 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20170118_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='not_in_school_before',
            field=models.BooleanField(default=False),
        ),
    ]
