# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_auto_20171113_1433'),
        ('students', '0008_auto_20171014_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='students',
            name='graduates_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.GraduatesStream'),
        ),
    ]
