# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20170118_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='time_to_school',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
