# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20171113_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='graduates_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stream.GraduatesStream'),
        ),
    ]
