# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20171115_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='offline_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
