# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_students_date_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_enrolled',
            field=models.DateField(auto_created=True),
        ),
    ]
