# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-26 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20180130_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='dropout_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
