# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_auto_20170122_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['gender']},
        ),
        migrations.AddField(
            model_name='students',
            name='guardian_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
