# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 17:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20170323_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['-gender']},
        ),
    ]
