# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_auto_20170410_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
