# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_auto_20161025_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parents',
            name='parent_id',
        ),
        migrations.AlterField(
            model_name='parents',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Students'),
        ),
    ]
