# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-03 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20170627_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='last_data_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
