# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-16 22:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0004_auto_20171204_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('test', models.BooleanField(default=False)),
                ('partners', models.ManyToManyField(blank=True, null=True, to='partner.Partner')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
