# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-15 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='left_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
