# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20170411_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='modified',
            field=models.DateTimeField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
