# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20170615_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.Stream'),
        ),
    ]
