# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_history_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
