# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20170411_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='left_description',
            field=models.CharField(blank=True, choices=[('DROP', 'Dropout'), ('TRANS', 'Transfer')], max_length=10, null=True),
        ),
    ]
