# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 11:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stream', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('modified', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(1, b'Present'), (0, b'Absent')], default=0)),
                ('cause_of_absence', models.CharField(blank=True, max_length=200, null=True)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.Stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Students')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
    ]
