# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_id', models.IntegerField(default=0)),
                ('student_id', models.IntegerField(default=0)),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('cause_of_absence', models.CharField(max_length=200)),
                ('class_id', models.IntegerField(default=0)),
                ('school_id', models.IntegerField(default=0)),
            ],
        ),
    ]
