# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0002_auto_20170109_1446'),
        ('students', '0003_auto_20170110_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, b'Present'), (0, b'Absent')], default=0)),
                ('cause_of_absence', models.CharField(max_length=200)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Students')),
            ],
        ),
    ]
