# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='cause_of_absence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
