# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20170112_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
