# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 14:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170311_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
