# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-27 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_stream_last_attendance'),
        ('attendance', '0003_auto_20170914_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('date', models.DateField()),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('present', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stream.Stream')),
            ],
        ),
    ]
