# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 16:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20170311_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
