# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('age', models.DateTimeField()),
                ('gender', models.CharField(max_length=200)),
                ('tsc_no', models.CharField(max_length=200)),
                ('bom_no', models.CharField(max_length=200)),
                ('qualifications', models.CharField(max_length=200)),
                ('date_started_teaching', models.DateTimeField()),
                ('joined_current_school', models.DateTimeField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Schools')),
                ('subjects', models.ManyToManyField(to='subjects.Subjects')),
            ],
        ),
    ]
