# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 06:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField(default=0)),
                ('teacher_type', models.CharField(choices=[('TSC', 'TSC'), ('BRD', 'BOARD')], default='TSC', max_length=3)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('ML', 'MALE'), ('FM', 'FEMALE')], default='ML', max_length=2)),
                ('tsc_no', models.CharField(max_length=200)),
                ('bom_no', models.CharField(max_length=200)),
                ('headteacher', models.BooleanField()),
                ('qualifications', models.CharField(choices=[('UNI', 'UNIVERSITY'), ('COL', 'COLLEGE')], default='COL', max_length=3)),
                ('date_started_teaching', models.DateField()),
                ('joined_current_school', models.DateField()),
                ('school_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.Schools')),
                ('subjects', models.ManyToManyField(null=True, to='subjects.Subjects')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
