# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='type',
            new_name='teacher_type',
        ),
    ]
