# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-16 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='subjects',
            field=models.ManyToManyField(to='subjects.Subjects'),
        ),
    ]
