# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20161025_2239'),
        ('subjects', '0002_remove_subjects_subject_id'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='bom_number',
            new_name='bom_no',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='tsc_number',
            new_name='tsc_no',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='teacher_id',
        ),
        migrations.AddField(
            model_name='teachers',
            name='school_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.Schools'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teachers',
            name='subjects',
            field=models.ManyToManyField(to='subjects.Subjects'),
        ),
    ]
