# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20170109_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='fstname',
            field=models.CharField(default='micha', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachers',
            name='lstname',
            field=models.CharField(default='kelvin', max_length=45),
            preserve_default=False,
        ),
    ]
