# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_auto_20170111_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='gender',
            field=models.CharField(choices=[(b'M', b'MALE'), (b'F', b'FEMALE')], default=b'ML', max_length=2),
        ),
    ]
