# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_auto_20170122_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='bom_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='date_started_teaching',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='headteacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='joined_current_school',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.Schools'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='subjects.Subjects'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='tsc_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
