# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_auto_20170413_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='headteacher',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='qualifications',
            field=models.CharField(blank=True, choices=[(b'UNI', b'UNIVERSITY'), (b'COL', b'COLLEGE')], default=b'COL', max_length=3, null=True),
        ),
    ]
