# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_auto_20170413_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
