# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-13 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_auto_20170413_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='headteacher',
            field=models.BooleanField(default=False),
        ),
    ]
